name: Pulse Issue Sync
description: Action to sync Pulse Issue tracking
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
outputs: {}
runs:
  using: node16
  main: ./entry.js