name: Pulse Cron
description: Repository operations on a schedule
inputs:
  app-id:
    description: The Application ID of the GitHub App to use for authentication
    required: true
  private-key:
    description: The Private Key of the GitHub App to use for authentication
    required: true
  installation-id:
    description: The Installation ID of the GitHub App to use for authentication
    required: true
outputs: {}
runs:
  using: node16
  main: ./entry.js