name: Pulse Changeset Feedback
description: Action to post the changeset feedback on a PR
inputs:
  marker:
    description: Marker to check if there is already a changeset posted on the PR
    default: '<!-- changeset-feedback -->'
    required: false
  diff-ref:
    description: The target branch to use to list the changes
    default: origin/main
    required: false
  issue-number:
    description: issue number of the PR
    required: true
  bot-username:
    description: username of the bot used to post comments on behalf of the action. Will be used when locating existing changeset feedback comments to update.
    default: github-actions[bot]
    required: false
  app-id:
    description: The Application ID of the GitHub App to use for authentication
    required: true
  private-key:
    description: The Private Key of the GitHub App to use for authentication
    required: true
  installation-id:
    description: The Installation ID of the GitHub App to use for authentication
    required: true
outputs: {}
runs:
  using: node16
  main: ./entry.js