name: PR
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issue_comment:
    types:
      - created

jobs:
  sync:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request || github.event.issue.pull_request }}

    steps:
      - uses: pulseflow/actions/pr-sync@v0.0.1
        with:
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN  }}
          app-id: ${{ secrets.PULSE_GOALIE_APPLICATION_ID }}
          private-key: ${{ secrets.PULSE_GOALIE_PRIVATE_KEY }}
          installation-id: ${{ secrets.PULSE_GOALIE_INSTALLATION_ID }}
          project-id: PVT_ejweyayeb1
          owning-teams: '@pulseflow/techdocs'